"""Sites supported by FanFicFare's adapters (generated from its getSiteExamples(), 4.62.0). Each entry: (name, hosts, identifier keys)."""

FFF_SITES = [
    ('adastrafanfic.com', ['adastrafanfic.com'], []),
    ('Adult-FanFiction.org', ['adult-fanfiction.org'], []),
    ('Alternate History', ['alternatehistory.com', 'althistory.com'], []),
    ('aneroticstory.com', ['aneroticstory.com'], []),
    ('archive.fanfictalk.com', ['archive.fanfictalk.com'], []),
    ('Archive of Our Own', ['archiveofourown.org', 'ao3.org', 'archiveofourown.com', 'archiveofourown.net', 'archiveofourown.gay'], []),
    ('ASexStories', ['asexstories.com'], []),
    ('ashwinder.sycophanthex.com', ['ashwinder.sycophanthex.com'], []),
    ('AsianFanfics', ['asianfanfics.com'], []),
    ('BDSM Library', ['bdsmlibrary.com'], []),
    ('bloodshedverse.com', ['bloodshedverse.com'], []),
    ('cfaarchive.org', ['cfaarchive.org'], []),
    ('chaos.sycophanthex.com', ['chaos.sycophanthex.com'], []),
    ('chireads.com', ['chireads.com'], []),
    ('chosentwofanfic.com', ['chosentwofanfic.com'], []),
    ('dark-solace.org', ['dark-solace.org'], []),
    ('DeviantArt', ['deviantart.com'], []),
    ('dokuga.com', ['dokuga.com'], []),
    ('dracoandginny.com', ['dracoandginny.com'], []),
    ('efpfanfic.net', ['efpfanfic.net'], []),
    ('erosnsappho.sycophanthex.com', ['erosnsappho.sycophanthex.com'], []),
    ('FanficAuthors', ['fanficauthors.net'], []),
    ('fanfics.me', ['fanfics.me'], []),
    ('FanFiction.Net', ['fanfiction.net'], []),
    ('fanfictions.fr', ['fanfictions.fr'], []),
    ('FanFiktion.de', ['fanfiktion.de'], []),
    ('Ficbook', ['ficbook.net'], []),
    ('Fiction.live', ['fiction.live'], []),
    ('fictionalley-archive.org', ['fictionalley-archive.org'], []),
    ('FictionHunt', ['fictionhunt.com'], []),
    ('Fictionmania', ['fictionmania.tv'], []),
    ('FictionPress', ['fictionpress.com'], []),
    ('ficwad.com', ['ficwad.com'], []),
    ('FimFiction', ['fimfiction.net'], []),
    ('fireflyfans.net', ['fireflyfans.net'], []),
    ('Questionable Questing', ['forum.questionablequesting.com'], []),
    ('SpaceBattles', ['forums.spacebattles.com'], []),
    ('Sufficient Velocity', ['forums.sufficientvelocity.com'], []),
    ('Giantessworld', ['giantessworld.net'], []),
    ('gluttonyfiction.com', ['gluttonyfiction.com'], []),
    ('Hentai Foundry', ['hentai-foundry.com'], []),
    ('imagine.e-fic.com', ['imagine.e-fic.com'], []),
    ('Inkbunny', ['inkbunny.net'], []),
    ('Kakuyomu', ['kakuyomu.jp'], []),
    ('ksarchive.com', ['ksarchive.com'], []),
    ('lcfanfic.com', ['lcfanfic.com'], []),
    ('libraryofmoria.com', ['libraryofmoria.com'], []),
    ('Literotica', ['literotica.com'], []),
    ('lumos.sycophanthex.com', ['lumos.sycophanthex.com'], []),
    ('masseffect2.in', ['masseffect2.in'], []),
    ('MCStories', ['mcstories.com'], []),
    ('MediaMiner', ['mediaminer.org'], []),
    ('midnightwhispers.net', ['midnightwhispers.net'], []),
    ('mtt.just-once.net', ['mtt.just-once.net'], []),
    ('mugglenetfanfiction.com', ['mugglenetfanfiction.com'], []),
    ('naiceanilme.net', ['naiceanilme.net'], []),
    ('narutofic.org', ['narutofic.org'], []),
    ('ncisfiction.com', ['ncisfiction.com'], []),
    ('ninelivesarchive.com', ['ninelivesarchive.com'], []),
    ('novelall.com', ['novelall.com'], []),
    ('NovelFull', ['novelfull.com', 'novelonlinefull.com'], []),
    ('novelonlinefull.com', ['novelonlinefull.com'], []),
    ('occlumency.sycophanthex.com', ['occlumency.sycophanthex.com'], []),
    ('phoenixsong.net', ['phoenixsong.net'], []),
    ('pmdfanfiction.com', ['pmdfanfiction.com'], []),
    ('potionsandsnitches.org', ['potionsandsnitches.org'], []),
    ('pretendercentre.com', ['pretendercentre.com'], []),
    ('psychfic.com', ['psychfic.com'], []),
    ('Quotev', ['quotev.com'], []),
    ('readonlymind.com', ['readonlymind.com'], []),
    ('Royal Road', ['royalroad.com', 'royalroadl.com'], []),
    ('samandjack.net', ['samandjack.net'], []),
    ('scifistories.com', ['scifistories.com'], []),
    ('Scribble Hub', ['scribblehub.com'], []),
    ('sheppardweir.com', ['sheppardweir.com'], []),
    ('sinful-dreams.com', ['sinful-dreams.com'], []),
    ('siye.co.uk', ['siye.co.uk'], []),
    ('SoFurry', ['sofurry.com'], []),
    ('spikeluver.com', ['spikeluver.com'], []),
    ('spiritfanfiction.com', ['spiritfanfiction.com'], []),
    ('SquidgeWorld', ['squidgeworld.org'], []),
    ('starslibrary.net', ['starslibrary.net'], []),
    ('storiesofarda.com', ['storiesofarda.com'], []),
    ('Stories Online', ['storiesonline.net'], []),
    ('storyroom.com', ['storyroom.com'], []),
    ('sunnydaleafterdark.com', ['sunnydaleafterdark.com'], []),
    ('superlove.sayitditto.net', ['superlove.sayitditto.net'], []),
    ('Syosetu', ['syosetu.com'], []),
    ('t.evancurrie.ca', ['t.evancurrie.ca'], []),
    ('TG Storytime', ['tgstorytime.com'], []),
    ('the-sietch.com', ['the-sietch.com'], []),
    ('thedelphicexpanse.com', ['thedelphicexpanse.com'], []),
    ('thehookupzone.net', ['thehookupzone.net'], []),
    ('themasque.net', ['themasque.net'], []),
    ('touchfluffytail.org', ['touchfluffytail.org'], []),
    ('trekfanfiction.net', ['trekfanfiction.net'], []),
    ('Twisting the Hellmouth', ['tthfanfic.org'], []),
    ('twilighted.net', ['twilighted.net'], []),
    ('utopiastories.com', ['utopiastories.com'], []),
    ('valentchamber.com', ['valentchamber.com'], []),
    ('voracity2.e-fic.com', ['voracity2.e-fic.com'], []),
    ('walkingtheplank.org', ['walkingtheplank.org'], []),
    ('Wattpad', ['wattpad.com'], []),
    ('whofic.com', ['whofic.com'], []),
    ('wolverineandrogue.com', ['wolverineandrogue.com'], []),
]
